// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbbjjfjohdgfxzxzqxtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiYmpqZmpvaGRnZnh6eHpxeHR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDM1MTIsImV4cCI6MjA2MDcxOTUxMn0.UCwofbbKzp9h0PznyjIFoXYotF6f1pjEHjqev3LOFCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);